This is for debugging this error when using the IGTD dataset in get_model_acc.py:


ds_train, ds_test = valid_datasets[train_index], valid_datasets[test_index] # valid_datasets is the list of datasets
IndexError: index 243 is out of bounds for axis 0 with size 243

In [1]:
import pandas as pd
import numpy as np
import os
from sklearn.model_selection import KFold
import csv
import sys
import csv
from random import sample
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.ensemble import StackingClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import KFold
from tqdm import tqdm
import re

In [2]:
def read_dataset(meta_dataset_path):
    results = []
    with open(meta_dataset_path, 'r') as file:
        reader = csv.reader(file)
        for count, row in enumerate(reader):
            # if its the first row then we save it as col_names and dont add to results
            if count == 0:
                col_names = row[1:]
            else:
                results.append(row[1:])
    
    return pd.DataFrame(results, columns=col_names)

In [11]:
maxes = {}

# make this a command line argument (if we use optim or default )
with open('optim_maxes.csv', 'r') as f:
    reader = csv.reader(f)
    for row in reader:
        key = int(row[0])
        values_str = ','.join(row[1:])
        values_str = values_str.strip()
        values = list(map(int, values_str.split(',')))
        maxes[key] = values

In [5]:
df = pd.read_csv('/users/guest/a/as2273/research_spring/dataset_embeddings_2.0/analyze_meta_models/meta_datasets/general_metadataset.csv')

df.replace(np.nan, 0, inplace=True)
df.replace(np.inf, 0, inplace=True)

X = []
y = []
valid_datasets = []

# built like this becuase not all the datsets work with each embedding so just using the index doesnt work 

for i in range(df.shape[0]):
    # check the first item in the ith row of df
    if df.loc[i, 'dataset'] in maxes:
        y.append(sample(maxes[df.loc[i, 'dataset']],k=1)[0])
        X.append(df.iloc[i, 1:].tolist())
        valid_datasets.append(df.loc[i, 'dataset'])
X = np.array(X)
y = np.array(y)
valid_datasets = np.array(valid_datasets)

In [30]:
# shuffle the datsets bfore calling train_meta_model
X_y = np.append(X, y.reshape(-1,1), axis=1)
everything = np.append(X_y, valid_datasets.reshape(-1,1), axis=1)
np.random.shuffle(everything)
new_valid_datasets = everything[:, -1]
new_y = everything[:, -2]
new_X = everything[:, :-2]

In [31]:
new_valid_datasets

array([130., 240., 378., 137., 306., 358., 254., 395., 206., 134., 248.,
       422., 447., 394., 102., 243., 153., 285., 115., 135., 160., 390.,
       103., 126., 341., 299., 355., 343., 222., 339., 426., 101., 392.,
       411., 174., 183.,  26., 331., 403., 110., 140., 139., 223., 432.,
       119., 212., 244.,  79.,  65., 118., 444.,  78., 361.,   7., 317.,
        91.,  24., 272., 114., 123., 316., 312., 399., 166., 409.,  10.,
        67., 269., 266., 433., 182., 211., 258., 321., 268.,  75.,  60.,
        18., 428., 451., 282., 384.,  68., 198., 367., 225.,  81.,  61.,
       230., 445.,  30., 259.,  32., 461., 404.,  62., 197., 333., 237.,
       357., 457., 281., 334., 220., 401., 313., 309., 325., 145., 369.,
       231., 393.,  35., 168., 242., 344., 454., 181.,   6., 260.,  93.,
       398., 185., 172., 131., 388., 142., 342., 241., 293., 274., 383.,
       144.,  95., 169., 322., 456., 116.,  17., 253., 122., 171., 420.,
       264., 113., 336., 437., 376., 385.,  97., 37

In [ ]:
X_y_valid = X_y_valid[:, :-1] # this is the X and y combined
X = X_y_valid[:, :-1]
y = X_y_valid[:, -1]
X_y_valid_datasets = X_y_valid_datasets.reshape(-1,1)
valid_datasets = X_y_valid_datasets

In [19]:
X_y_valid_datasets

array([[338.],
       [419.],
       [297.],
       [219.],
       [376.],
       [215.],
       [417.],
       [456.],
       [372.],
       [410.],
       [142.],
       [ 53.],
       [138.],
       [375.],
       [260.],
       [399.],
       [287.],
       [ 99.],
       [293.],
       [318.],
       [ 64.],
       [313.],
       [437.],
       [ 18.],
       [341.],
       [123.],
       [209.],
       [119.],
       [323.],
       [292.],
       [229.],
       [268.],
       [181.],
       [244.],
       [144.],
       [254.],
       [211.],
       [ 87.],
       [202.],
       [444.],
       [153.],
       [355.],
       [ 54.],
       [208.],
       [134.],
       [226.],
       [ 30.],
       [299.],
       [145.],
       [267.],
       [383.],
       [426.],
       [ 35.],
       [183.],
       [ 28.],
       [207.],
       [ 61.],
       [408.],
       [298.],
       [130.],
       [430.],
       [320.],
       [257.],
       [193.],
       [245.],
       [345.],
       [22

In [22]:
new_new_valid_datasets = np.squeeze(new_valid_datasets)

In [23]:
new_new_valid_datasets

array([338., 419., 297., 219., 376., 215., 417., 456., 372., 410., 142.,
        53., 138., 375., 260., 399., 287.,  99., 293., 318.,  64., 313.,
       437.,  18., 341., 123., 209., 119., 323., 292., 229., 268., 181.,
       244., 144., 254., 211.,  87., 202., 444., 153., 355.,  54., 208.,
       134., 226.,  30., 299., 145., 267., 383., 426.,  35., 183.,  28.,
       207.,  61., 408., 298., 130., 430., 320., 257., 193., 245., 345.,
       221., 101., 266., 412.,  81.,  62., 272., 247., 325.,  44., 241.,
        59., 213.,  94., 109., 114., 197., 321., 447., 360., 427., 415.,
       170., 278., 396., 461., 369., 311., 462., 390.,  92., 288., 151.,
       212., 251.,  74.,  21., 332.,  41., 388., 276., 146., 402., 312.,
       234., 328., 223., 364., 253., 137., 329., 222.,  55., 192., 262.,
       259., 205., 389.,   6., 350., 185.,  25.,  34., 100., 394., 324.,
       279., 186., 307., 347., 366., 135., 304.,  85., 124.,  82., 149.,
       200.,  43., 282., 359.,  67.,  52., 362., 25

In [20]:
valid_datasets

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105,
       106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
       119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 130, 131, 132,
       133, 134, 135, 137, 138, 139, 140, 141, 142, 144, 145, 146, 149,
       150, 151, 152, 153, 156, 158, 159, 160, 163, 164, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 19

In [15]:
kfold_num = 10
def train_meta_model(sk_algorithm, X, y, valid_datasets, maxes, kfold_num=10):
	accuracies = []
	kf = KFold(n_splits=kfold_num)
	kf.get_n_splits(X)
	for train_index, test_index in tqdm(kf.split(X)):
		X_train, X_test = X[train_index], X[test_index]
		y_train, y_test = y[train_index], y[test_index] # dont use y_test
		ds_train, ds_test = valid_datasets[train_index], valid_datasets[test_index] # valid_datasets is the list of datasets
		# IndexError: index 243 is out of bounds for axis 0 with size 243 <--- no idea what this is from. but its annyoing 
		sk_algorithm.fit(X_train, y_train)
		y_pred = sk_algorithm.predict(X_test)
		correct = 0
		print('ds_test', ds_test)
		print('y_pred', y_pred)
		for ds, prediction in zip(ds_test, y_pred):
			print('ds', ds)
			print('prediction', prediction)
			if prediction in maxes[ds]:
				correct += 1
		accuracies.append(correct/len(ds_test))
	return max(accuracies) # do I want to return accuracies max?

In [16]:
results_arr = []
    # Random Forest
rf = RandomForestClassifier(n_estimators=100, max_depth=2, random_state=0)
rf_accuracies = train_meta_model(rf, X, y, valid_datasets, maxes, kfold_num=kfold_num)
results_arr.append(np.mean(rf_accuracies))
print(f'rf accuracy: {round(np.mean(rf_accuracies)*100,2)}%', flush=True)

3it [00:00, 10.71it/s]

ds_test [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44]
y_pred [15.  7. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15.  7. 14. 14. 14.  7. 15.
  7. 15.  7. 15. 14. 15. 15. 15. 15. 15.  5. 15. 15. 14. 15. 14. 14. 15.
 15. 15. 15. 15.  7. 15. 15. 15.]
ds 1
prediction 15.0
ds 2
prediction 7.0
ds 3
prediction 15.0
ds 4
prediction 15.0
ds 5
prediction 15.0
ds 6
prediction 15.0
ds 7
prediction 15.0
ds 8
prediction 15.0
ds 9
prediction 15.0
ds 10
prediction 15.0
ds 11
prediction 15.0
ds 12
prediction 15.0
ds 13
prediction 7.0
ds 14
prediction 14.0
ds 15
prediction 14.0
ds 16
prediction 14.0
ds 17
prediction 7.0
ds 18
prediction 15.0
ds 19
prediction 7.0
ds 20
prediction 15.0
ds 21
prediction 7.0
ds 22
prediction 15.0
ds 23
prediction 14.0
ds 24
prediction 15.0
ds 25
prediction 15.0
ds 26
prediction 15.0
ds 27
prediction 15.0
ds 28
prediction 15.0
ds 29
prediction 5.0
ds 30
prediction 15.0
ds 31
prediction 15.0
ds 

5it [00:00, 10.99it/s]

ds_test [135 137 138 139 140 141 142 144 145 146 149 150 151 152 153 156 158 159
 160 163 164 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188]
y_pred [15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 14. 15. 15.  7. 15.  0.
 14. 15. 15. 15. 15. 15. 15. 15. 15. 14. 15. 15. 15. 15. 15.  7. 15. 15.
 15. 15. 15. 15. 15. 15. 15. 15.]
ds 135
prediction 15.0
ds 137
prediction 15.0
ds 138
prediction 15.0
ds 139
prediction 15.0
ds 140
prediction 15.0
ds 141
prediction 15.0
ds 142
prediction 15.0
ds 144
prediction 15.0
ds 145
prediction 15.0
ds 146
prediction 15.0
ds 149
prediction 15.0
ds 150
prediction 15.0
ds 151
prediction 14.0
ds 152
prediction 15.0
ds 153
prediction 15.0
ds 156
prediction 7.0
ds 158
prediction 15.0
ds 159
prediction 0.0
ds 160
prediction 14.0
ds 163
prediction 15.0
ds 164
prediction 15.0
ds 166
prediction 15.0
ds 167
prediction 15.0
ds 168
prediction 15.0
ds 169
prediction 15.0
ds 170
prediction 15.0
ds 171
prediction 15.0
ds 172

9it [00:00, 11.27it/s]

ds_test [277 278 279 280 281 282 283 284 285 286 287 288 289 290 292 293 295 296
 297 298 299 301 302 303 304 306 307 308 309 310 311 312 313 314 315 316
 317 318 320 321 322 323 324 325]
y_pred [15.  0. 15. 14. 14. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15.
 15. 14. 15. 15. 15.  7. 14. 15. 15. 15. 15.  7. 15. 15. 15. 15. 15. 15.
 15. 15. 15. 15. 15. 15. 15.  0.]
ds 277
prediction 15.0
ds 278
prediction 0.0
ds 279
prediction 15.0
ds 280
prediction 14.0
ds 281
prediction 14.0
ds 282
prediction 15.0
ds 283
prediction 15.0
ds 284
prediction 15.0
ds 285
prediction 15.0
ds 286
prediction 15.0
ds 287
prediction 15.0
ds 288
prediction 15.0
ds 289
prediction 15.0
ds 290
prediction 15.0
ds 292
prediction 15.0
ds 293
prediction 15.0
ds 295
prediction 15.0
ds 296
prediction 15.0
ds 297
prediction 15.0
ds 298
prediction 14.0
ds 299
prediction 15.0
ds 301
prediction 15.0
ds 302
prediction 15.0
ds 303
prediction 7.0
ds 304
prediction 14.0
ds 306
prediction 15.0
ds 307
prediction 15.0
ds 308

10it [00:00, 11.11it/s]

ds_test [418 419 420 421 422 423 426 427 428 429 430 431 432 433 434 435 436 437
 438 439 440 442 443 444 445 447 448 449 450 451 452 453 454 455 456 457
 458 459 460 461 462 464 466]
y_pred [14.  7. 15. 15. 15. 14. 14. 15. 14. 15. 14. 15. 15. 15.  7. 14. 15. 13.
 14. 15. 15. 15. 15. 14.  7. 14. 15. 15. 15. 15. 15. 14.  7. 14.  0. 15.
 15. 15. 14. 14. 15. 15.  0.]
ds 418
prediction 14.0
ds 419
prediction 7.0
ds 420
prediction 15.0
ds 421
prediction 15.0
ds 422
prediction 15.0
ds 423
prediction 14.0
ds 426
prediction 14.0
ds 427
prediction 15.0
ds 428
prediction 14.0
ds 429
prediction 15.0
ds 430
prediction 14.0
ds 431
prediction 15.0
ds 432
prediction 15.0
ds 433
prediction 15.0
ds 434
prediction 7.0
ds 435
prediction 14.0
ds 436
prediction 15.0
ds 437
prediction 13.0
ds 438
prediction 14.0
ds 439
prediction 15.0
ds 440
prediction 15.0
ds 442
prediction 15.0
ds 443
prediction 15.0
ds 444
prediction 14.0
ds 445
prediction 7.0
ds 447
prediction 14.0
ds 448
prediction 15.0
ds 449
predicti

In [62]:
results_arr = []
    # Random Forest
rf = RandomForestClassifier(n_estimators=100, max_depth=2, random_state=0)
rf_accuracies = train_meta_model(rf, X, y, valid_datasets, maxes, kfold_num=kfold_num)
results_arr.append(np.mean(rf_accuracies))
print(f'rf accuracy: {round(np.mean(rf_accuracies)*100,2)}%', flush=True)

# # Logistic Regression
# lr = LogisticRegression(random_state=0, solver='lbfgs', multi_class='multinomial', max_iter=100000)
# lr_accuracies = train_meta_model(lr, X, y, valid_datasets, maxes, kfold_num=kfold_num)
# results_arr.append(np.mean(lr_accuracies))
# print(f'lr accuracy: {round(np.mean(lr_accuracies)*100,2)}%', flush=True)

# SVM
svm = SVC(gamma='auto')
svm_accuracies = train_meta_model(svm, X, y, valid_datasets, maxes, kfold_num=kfold_num)
results_arr.append(np.mean(svm_accuracies))
print(f'svm accuracy: {round(np.mean(svm_accuracies)*100,2)}%', flush=True)

# KNN
knn = KNeighborsClassifier(n_neighbors=3)
knn_accuracies = train_meta_model(knn, X, y, valid_datasets, maxes, kfold_num=kfold_num)
results_arr.append(np.mean(knn_accuracies))
print(f'knn accuracy: {round(np.mean(knn_accuracies)*100,2)}%', flush=True)

# Naive Bayes
nb = GaussianNB()
nb_accuracies = train_meta_model(nb, X, y, valid_datasets, maxes, kfold_num=kfold_num)
results_arr.append(np.mean(nb_accuracies))
print(f'nb accuracy: {round(np.mean(nb_accuracies)*100,2)}%')

# Decision Tree
dt = DecisionTreeClassifier(random_state=0)
dt_accuracies = train_meta_model(dt, X, y, valid_datasets, maxes, kfold_num=kfold_num)
results_arr.append(np.mean(dt_accuracies))
print(f'dt accuracy: {round(np.mean(dt_accuracies)*100,2)}%')

# AdaBoost
ab = AdaBoostClassifier(n_estimators=100, random_state=0)
ab_accuracies = train_meta_model(ab, X, y, valid_datasets, maxes, kfold_num=kfold_num)
results_arr.append(np.mean(ab_accuracies))
print(f'ab accuracy: {round(np.mean(ab_accuracies)*100,2)}%')

# Gradient Boosting
gb = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=1, random_state=0,)
gb_accuracies = train_meta_model(gb, X, y, valid_datasets, maxes, kfold_num=kfold_num)
results_arr.append(np.mean(gb_accuracies))
print(f'gb accuracy: {round(np.mean(gb_accuracies)*100,2)}%')

# Neural Network
nn = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1, max_iter=100000000)
# print out and check all the types of what we pass into the train_meta_model function
nn_accuracies = train_meta_model(nn, X, y, valid_datasets, maxes, kfold_num=kfold_num)
results_arr.append(np.mean(nn_accuracies))
print(f'nn accuracy: {round(np.mean(nn_accuracies)*100,2)}%')

# Bagging
bg = BaggingClassifier(estimator=DecisionTreeClassifier(), n_estimators=10, random_state=0)
bg_accuracies = train_meta_model(bg, X, y, valid_datasets, maxes, kfold_num=kfold_num)
results_arr.append(np.mean(bg_accuracies))
print(f'bg accuracy: {round(np.mean(bg_accuracies)*100,2)}%')

# Extra Trees
et = ExtraTreesClassifier(n_estimators=100, max_depth=None, min_samples_split=2, random_state=0)
et_accuracies = train_meta_model(et, X, y, valid_datasets, maxes, kfold_num=kfold_num)
results_arr.append(np.mean(et_accuracies))
print(f'et accuracy: {round(np.mean(et_accuracies)*100,2)}%')

# Voting Classifier
vc = VotingClassifier(estimators=[('rf', rf),   ('svm', svm), ('knn', knn), ('nb', nb), ('dt', dt), ('ab', ab), ('gb', gb), ('nn', nn), ('bg', bg), ('et', et)], voting='hard')
vc_accuracies = train_meta_model(vc, X, y, valid_datasets, maxes, kfold_num=kfold_num)
results_arr.append(np.mean(vc_accuracies))
print(f'vc accuracy: {round(np.mean(vc_accuracies)*100,2)}%')

10it [00:07,  1.36it/s]

rf accuracy: 61.36%



10it [03:47, 22.79s/it]

svm accuracy: 65.91%



10it [00:04,  2.41it/s]

knn accuracy: 34.09%



10it [00:08,  1.11it/s]


nb accuracy: 31.82%


10it [02:07, 12.78s/it]


dt accuracy: 47.73%


10it [23:42, 142.27s/it]


ab accuracy: 63.64%


2it [1:01:21, 1840.63s/it]


KeyboardInterrupt: 